version: '3.7'

services:

  fiap-clientes-api:
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      - fiap-clientes-api-net
    restart: always
    depends_on:
      - fiap-clientes-api-db-mysql
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: fiap-clientes-api-db-mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: fiap
      DATABASE_PASSWORD: fiap
      DATABASE_DATABASE: fiap-clientes

  fiap-clientes-api-db-mysql:
    image: mysql:8.0
    restart: always
    networks: 
      - fiap-clientes-api-net
    volumes:
      - mysql_data_fiap_clientes:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiap-clientes
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap

volumes:
  mysql_data_fiap_clientes: {}

networks:
  fiap-clientes-api-net:
    driver: bridge