apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap-produtos-api-config
  namespace: fiap-produtos-api
  labels:
    name: fiap-produtos-api-config
data:
  DATABASE_HOST: "terraform-20241130112944620700000004.cqkwnkbplfjh.us-east-1.rds.amazonaws.com"
  DATABASE_PORT: "3306"
  DATABASE_DATABASE: "produtos"
  APPLICATION_PORT: "3001"
