apiVersion: v1
kind: Service
metadata:
  name: fiap-produtos-api-service
  namespace: fiap-produtos-api

spec:
  type: LoadBalancer
  selector:
    app: fiap-produtos-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001